package pe.upeu.biblioandes.presentation.theme

import androidx.compose.ui.graphics.Color

// Paleta propia de BiblioAndes: terracota andina (primario), arcilla (secundario)
// y oro viejo (terciario), con fondos cálidos en lugar de grises neutros.

// ---------- Modo claro ----------
val PrimaryLight = Color(0xFF8C4A2F)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFFFFDBCF)
val OnPrimaryContainerLight = Color(0xFF380D00)
val SecondaryLight = Color(0xFF77574B)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFFFDBCF)
val OnSecondaryContainerLight = Color(0xFF2C160C)
val TertiaryLight = Color(0xFF6B5E10)
val OnTertiaryLight = Color(0xFFFFFFFF)
val TertiaryContainerLight = Color(0xFFF5E287)
val OnTertiaryContainerLight = Color(0xFF211B00)
val BackgroundLight = Color(0xFFFFF8F6)
val OnBackgroundLight = Color(0xFF231917)
val SurfaceLight = Color(0xFFFFF8F6)
val OnSurfaceLight = Color(0xFF231917)
val SurfaceVariantLight = Color(0xFFF5DED6)
val OnSurfaceVariantLight = Color(0xFF53433E)
val OutlineLight = Color(0xFF85736D)
val OutlineVariantLight = Color(0xFFD8C2BA)
val SurfaceContainerLowestLight = Color(0xFFFFFFFF)
val SurfaceContainerLowLight = Color(0xFFFFF1ED)
val SurfaceContainerLight = Color(0xFFFCEAE5)
val SurfaceContainerHighLight = Color(0xFFF7E4DF)
val SurfaceContainerHighestLight = Color(0xFFF1DFDA)

// ---------- Modo oscuro ----------
val PrimaryDark = Color(0xFFFFB59C)
val OnPrimaryDark = Color(0xFF561F07)
val PrimaryContainerDark = Color(0xFF71341A)
val OnPrimaryContainerDark = Color(0xFFFFDBCF)
val SecondaryDark = Color(0xFFE7BDAD)
val OnSecondaryDark = Color(0xFF442A1F)
val SecondaryContainerDark = Color(0xFF5D4034)
val OnSecondaryContainerDark = Color(0xFFFFDBCF)
val TertiaryDark = Color(0xFFD8C66E)
val OnTertiaryDark = Color(0xFF383000)
val TertiaryContainerDark = Color(0xFF524600)
val OnTertiaryContainerDark = Color(0xFFF5E287)
val BackgroundDark = Color(0xFF1A110F)
val OnBackgroundDark = Color(0xFFF1DFDA)
val SurfaceDark = Color(0xFF1A110F)
val OnSurfaceDark = Color(0xFFF1DFDA)
val SurfaceVariantDark = Color(0xFF53433E)
val OnSurfaceVariantDark = Color(0xFFD8C2BA)
val OutlineDark = Color(0xFFA08C86)
val OutlineVariantDark = Color(0xFF53433E)
val SurfaceContainerLowestDark = Color(0xFF140C0A)
val SurfaceContainerLowDark = Color(0xFF231917)
val SurfaceContainerDark = Color(0xFF271D1B)
val SurfaceContainerHighDark = Color(0xFF322825)
val SurfaceContainerHighestDark = Color(0xFF3D322F)
